export const tripsByRange = {
  Today: [
    {
      id: 'TRP-84729',
      status: 'Completed',
      tripDateTime: '12 Oct, 10:30 PM',
      distanceKm: 42.2,
      tripTypeLabel: 'Trip 2',
      totalEarnings: 210,
      toll: 0,
      tip: 0,
      cash: 210,
      adjustedAmount: 0,
    },
    {
      id: 'TRP-84730',
      status: 'Completed',
      tripDateTime: '12 Oct, 10:30 PM',
      distanceKm: 42.2,
      tripTypeLabel: 'Trip 2',
      totalEarnings: 210,
      toll: 0,
      tip: 0,
      cash: 210,
      adjustedAmount: 0,
    },
  ],
  Week: [
    {
      id: 'TRP-84711',
      status: 'Completed',
      tripDateTime: '11 Oct, 9:15 PM',
      distanceKm: 36.4,
      tripTypeLabel: 'Trip 3',
      totalEarnings: 860,
      toll: 30,
      tip: 20,
      cash: 790,
      adjustedAmount: 20,
    },
    {
      id: 'TRP-84708',
      status: 'Pending',
      tripDateTime: '10 Oct, 8:50 PM',
      distanceKm: 18.9,
      tripTypeLabel: 'Trip 1',
      totalEarnings: 320,
      toll: 0,
      tip: 0,
      cash: 320,
      adjustedAmount: 0,
    },
  ],
  Month: [
    {
      id: 'TRP-84029',
      status: 'Completed',
      tripDateTime: '04 Oct, 11:20 PM',
      distanceKm: 29.1,
      tripTypeLabel: 'Trip 2',
      totalEarnings: 1240,
      toll: 80,
      tip: 60,
      cash: 1100,
      adjustedAmount: 0,
    },
    {
      id: 'TRP-83991',
      status: 'Cancelled',
      tripDateTime: '02 Oct, 7:45 PM',
      distanceKm: 0,
      tripTypeLabel: 'Trip 0',
      totalEarnings: 0,
      toll: 0,
      tip: 0,
      cash: 0,
      adjustedAmount: 0,
    },
  ],
};
