import { StyleSheet } from 'react-native';
import { fontPixel, heightPixel, widthPixel } from '../../utility/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  header: {
    height: heightPixel(62),
    paddingHorizontal: widthPixel(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconWrap: {
    height: heightPixel(38),
    width: widthPixel(38),
    borderRadius: widthPixel(50),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: fontPixel(20),
  },
  contentContainer: {
    paddingHorizontal: widthPixel(24),
    paddingTop: heightPixel(16),
    paddingBottom: heightPixel(16),
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: widthPixel(8),
  },
  filterItem: {
    flex: 1,
  },
  filterLabel: {
    color: '#9B9B9B',
    fontSize: fontPixel(12),
    marginBottom: heightPixel(4),
  },
  selectorButton: {
    height: heightPixel(43),
    borderWidth: 1,
    borderColor: '#DADADA',
    backgroundColor: '#FFFFFF',
    borderRadius: widthPixel(4),
    paddingHorizontal: widthPixel(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectorValue: {
    color: '#3B3B3B',
    fontSize: fontPixel(14),
  },
  summaryCard: {
    marginTop: heightPixel(8),
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  summaryTop: {
    minHeight: heightPixel(76),
    borderWidth: 1,
    borderColor: '#DDDDDD',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: widthPixel(8),
    justifyContent: 'space-between',
    paddingHorizontal: widthPixel(8),
    paddingVertical: heightPixel(6),
  },
  summaryTopItem: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryTopLabel: {
    color: '#8E8E8E',
    fontSize: fontPixel(12),
  },
  summaryTopValue: {
    marginTop: heightPixel(1),
    color: '#1A1A1A',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  kpiGrid: {
    paddingVertical: heightPixel(8),
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: heightPixel(6),
  },
  kpiCard: {
    width: '48.8%',
    borderWidth: 1,
    borderColor: '#E7E7E7',
    borderRadius: widthPixel(10),
    backgroundColor: '#FBFBFB',
    minHeight: heightPixel(66),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(6),
    paddingVertical: heightPixel(4),
  },
  kpiLabel: {
    color: '#666666',
    fontSize: fontPixel(12),
    textAlign: 'center',
  },
  kpiValue: {
    marginTop: heightPixel(1),
    color: '#1A1A1A',
    fontSize: fontPixel(14),
  },
  tabsWrap: {
    marginTop: heightPixel(8),
    backgroundColor: '#FFFFFF',
    borderRadius: widthPixel(6),
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  tabButton: {
    flex: 1,
    minHeight: heightPixel(32),
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  tabButtonActive: {
    borderBottomColor: '#000088',
    // backgroundColor: '#F4F6FF',
  },
  tabIndicator: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    height: 3,
    backgroundColor: '#000088',
  },
  tabText: {
    color: 'black',
    fontSize: fontPixel(14),
    fontWeight: '500',
  },
  tabTextActive: {
    color: '#000088',
    fontWeight: '700',
  },
  rowsCard: {
    marginTop: heightPixel(8),
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: widthPixel(6),
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  rowItem: {
    paddingHorizontal: widthPixel(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EFEFEF',
    minHeight: heightPixel(48),
  },
  rowItemLast: {
    borderBottomWidth: 0,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: widthPixel(22),
  },
  badge: {
    width: widthPixel(27),
    height: heightPixel(27),
    borderRadius: widthPixel(50),
    borderWidth: 1,
    borderColor: '#BDBDBD',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9F9F9',
  },
  badgeText: {
    color: '#6B6B6B',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  rowTitle: {
    marginLeft: widthPixel(7),
    color: '#262626',
    fontSize: fontPixel(14),
  },
  rowTitleStrong: {
    fontWeight: '700',
  },
  rowAmount: {
    color: '#141414',
    fontSize: fontPixel(18),
  },
});
