import { StyleSheet } from 'react-native';
import { fontPixel, heightPixel, widthPixel } from '../../utility/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  header: {
    height: heightPixel(62),
    paddingHorizontal: widthPixel(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconWrap: {
    height: heightPixel(38),
    width: widthPixel(38),
    borderRadius: widthPixel(50),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: fontPixel(20),
  },
  contentContainer: {
    paddingHorizontal: widthPixel(24),
    paddingTop: heightPixel(16),
    paddingBottom: heightPixel(16),
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: widthPixel(8),
  },
  filterRowTopGap: {
    marginTop: heightPixel(8),
  },
  filterItem: {
    flex: 1,
  },
  filterLabel: {
    color: '#9B9B9B',
    fontSize: fontPixel(12),
    marginBottom: heightPixel(4),
  },
  selectorButton: {
    height: heightPixel(43),
    borderWidth: 1,
    borderColor: '#DADADA',
    backgroundColor: '#FFFFFF',
    borderRadius: widthPixel(4),
    paddingHorizontal: widthPixel(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectorValue: {
    color: '#3B3B3B',
    fontSize: fontPixel(14),
  },
  summaryCard: {
    marginTop: heightPixel(8),
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  summaryTop: {
    minHeight: heightPixel(76),
    borderWidth: 1,
    borderColor: '#DDDDDD',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: widthPixel(8),
    justifyContent: 'space-between',
    paddingHorizontal: widthPixel(8),
    paddingVertical: heightPixel(6),
  },
  summaryTopItem: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryTopLabel: {
    color: '#8E8E8E',
    fontSize: fontPixel(12),
  },
  summaryTopValue: {
    marginTop: heightPixel(1),
    color: '#1A1A1A',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  kpiGrid: {
    paddingVertical: heightPixel(8),
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: heightPixel(6),
  },
  kpiCard: {
    width: '48.8%',
    borderWidth: 1,
    borderColor: '#E7E7E7',
    borderRadius: widthPixel(10),
    backgroundColor: '#FBFBFB',
    minHeight: heightPixel(66),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(6),
    paddingVertical: heightPixel(4),
  },
  kpiLabel: {
    color: '#666666',
    fontSize: fontPixel(12),
    textAlign: 'center',
  },
  kpiValue: {
    marginTop: heightPixel(1),
    color: '#1A1A1A',
    fontSize: fontPixel(14),
  },
  tabsWrap: {
    marginTop: heightPixel(8),
    backgroundColor: '#FFFFFF',
    borderRadius: widthPixel(6),
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  tabButton: {
    flex: 1,
    minHeight: heightPixel(32),
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  tabButtonActive: {
    borderBottomColor: '#000088',
    // backgroundColor: '#F4F6FF',
  },
  tabIndicator: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    height: 3,
    backgroundColor: '#000088',
  },
  tabText: {
    color: 'black',
    fontSize: fontPixel(14),
    fontWeight: '500',
  },
  tabTextActive: {
    color: '#000088',
    fontWeight: '700',
  },
  rowsCard: {
    marginTop: heightPixel(8),
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: widthPixel(6),
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  rowItem: {
    paddingHorizontal: widthPixel(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EFEFEF',
    minHeight: heightPixel(48),
  },
  rowItemLast: {
    borderBottomWidth: 0,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: widthPixel(22),
  },
  badge: {
    width: widthPixel(27),
    height: heightPixel(27),
    borderRadius: widthPixel(50),
    borderWidth: 1,
    borderColor: '#BDBDBD',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9F9F9',
  },
  badgeText: {
    color: '#6B6B6B',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  rowTitle: {
    marginLeft: widthPixel(7),
    color: '#262626',
    fontSize: fontPixel(14),
  },
  rowTitleStrong: {
    fontWeight: '700',
  },
  rowAmount: {
    color: '#141414',
    fontSize: fontPixel(18),
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(18),
  },
  durationModalCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: widthPixel(10),
    borderWidth: 1,
    borderColor: '#E1E1E1',
    paddingHorizontal: widthPixel(14),
    paddingVertical: heightPixel(14),
  },
  dropdownModalCard: {
    width: '100%',
    maxHeight: '72%',
    backgroundColor: '#FFFFFF',
    borderRadius: widthPixel(10),
    borderWidth: 1,
    borderColor: '#E1E1E1',
    paddingHorizontal: widthPixel(14),
    paddingVertical: heightPixel(14),
  },
  monthYearModalCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: widthPixel(10),
    borderWidth: 1,
    borderColor: '#E1E1E1',
    paddingHorizontal: widthPixel(14),
    paddingVertical: heightPixel(14),
  },
  modalTitle: {
    color: '#151515',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  modalFieldGroup: {
    marginTop: heightPixel(12),
  },
  modalFieldLabel: {
    color: '#555555',
    fontSize: fontPixel(12),
    fontWeight: '600',
    marginBottom: heightPixel(6),
  },
  modalSelectorButton: {
    height: heightPixel(42),
    borderWidth: 1,
    borderColor: '#DADADA',
    borderRadius: widthPixel(8),
    backgroundColor: '#FFFFFF',
    paddingHorizontal: widthPixel(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalSelectorValue: {
    color: '#2E2E2E',
    fontSize: fontPixel(13),
    fontWeight: '500',
  },
  modalDropdownList: {
    maxHeight: heightPixel(200),
    marginTop: heightPixel(8),
  },
  modalDropdownListContent: {
    rowGap: heightPixel(8),
    paddingBottom: heightPixel(2),
  },
  durationOptionsWrap: {
    marginTop: heightPixel(10),
    rowGap: heightPixel(8),
  },
  dropdownList: {
    marginTop: heightPixel(10),
  },
  dropdownListContent: {
    rowGap: heightPixel(8),
    paddingBottom: heightPixel(4),
  },
  durationOptionItem: {
    minHeight: heightPixel(40),
    borderWidth: 1,
    borderColor: '#DEDEDE',
    borderRadius: widthPixel(8),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAFAFA',
  },
  durationOptionItemActive: {
    borderColor: '#000088',
    backgroundColor: '#EDF0FF',
  },
  durationOptionText: {
    color: '#2E2E2E',
    fontSize: fontPixel(13),
    fontWeight: '500',
  },
  durationOptionTextActive: {
    color: '#000088',
    fontWeight: '700',
  },
  monthGrid: {
    marginTop: heightPixel(10),
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: widthPixel(8),
  },
  monthChip: {
    width: '22%',
    height: heightPixel(34),
    borderWidth: 1,
    borderColor: '#DEDEDE',
    borderRadius: widthPixel(6),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAFAFA',
  },
  monthChipActive: {
    borderColor: '#000088',
    backgroundColor: '#EDF0FF',
  },
  monthChipText: {
    color: '#444444',
    fontSize: fontPixel(11),
    fontWeight: '500',
  },
  monthChipTextActive: {
    color: '#000088',
    fontWeight: '700',
  },
  yearInputSection: {
    marginTop: heightPixel(12),
  },
  yearInputLabel: {
    color: '#555555',
    fontSize: fontPixel(12),
    fontWeight: '600',
    marginBottom: heightPixel(6),
  },
  yearInput: {
    height: heightPixel(40),
    borderWidth: 1,
    borderColor: '#DADADA',
    borderRadius: widthPixel(8),
    backgroundColor: '#FFFFFF',
    paddingHorizontal: widthPixel(10),
    color: '#1F1F1F',
    fontSize: fontPixel(13),
    fontWeight: '500',
  },
  yearList: {
    marginTop: heightPixel(10),
    columnGap: widthPixel(8),
  },
  yearChip: {
    minWidth: widthPixel(62),
    height: heightPixel(34),
    borderWidth: 1,
    borderColor: '#DEDEDE',
    borderRadius: widthPixel(6),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(10),
    backgroundColor: '#FAFAFA',
  },
  yearChipActive: {
    borderColor: '#000088',
    backgroundColor: '#EDF0FF',
  },
  yearChipText: {
    color: '#444444',
    fontSize: fontPixel(11),
    fontWeight: '500',
  },
  yearChipTextActive: {
    color: '#000088',
    fontWeight: '700',
  },
  yearDialerWrap: {
    marginTop: heightPixel(8),
    height: heightPixel(40) * 5,
    borderWidth: 1,
    borderColor: '#DADADA',
    borderRadius: widthPixel(8),
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    position: 'relative',
  },
  yearDialerContent: {
    paddingVertical: heightPixel(80),
  },
  yearDialerItem: {
    height: heightPixel(40),
    alignItems: 'center',
    justifyContent: 'center',
  },
  yearDialerText: {
    color: '#666666',
    fontSize: fontPixel(13),
    fontWeight: '500',
  },
  yearDialerTextActive: {
    color: '#000088',
    fontWeight: '700',
  },
  yearDialerHighlight: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: heightPixel(80),
    height: heightPixel(40),
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#CCD6FF',
    backgroundColor: 'rgba(237, 240, 255, 0.35)',
  },
  modalActionRow: {
    marginTop: heightPixel(14),
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  modalActionButton: {
    minWidth: widthPixel(82),
    height: heightPixel(36),
    borderRadius: widthPixel(6),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(10),
  },
  modalCancelButton: {
    borderWidth: 1,
    borderColor: '#D2D2D2',
    backgroundColor: '#FFFFFF',
    marginRight: widthPixel(8),
  },
  modalCancelButtonText: {
    color: '#555555',
    fontSize: fontPixel(12),
    fontWeight: '600',
  },
  modalDoneButton: {
    backgroundColor: '#000088',
  },
  modalDoneButtonText: {
    color: '#FFFFFF',
    fontSize: fontPixel(12),
    fontWeight: '700',
  },
});
