import { StyleSheet } from 'react-native';
import { fontPixel, heightPixel, widthPixel } from '../../utility/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  header: {
    height: heightPixel(70),
    paddingHorizontal: widthPixel(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconWrap: {
    height: heightPixel(38),
    width: widthPixel(38),
    borderRadius: widthPixel(50),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: fontPixel(20),
    fontWeight: '500',
  },
  contentWrap: {
    flex: 1,
    // paddingHorizontal: widthPixel(10),
    paddingTop: heightPixel(10),
  },
  headerControlsWrap: {
    paddingHorizontal: widthPixel(10),
  },
  filterWrap: {
    borderRadius: widthPixel(6),
    paddingHorizontal: widthPixel(8),
    paddingVertical: heightPixel(8),
  },
  filterLabel: {
    color: '#8D8D8D',
    fontSize: fontPixel(12),
    marginBottom: heightPixel(2),
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  monthSelector: {
    flex: 1,
    height: heightPixel(43),
    borderWidth: 1,
    borderColor: '#DFDFDF',
    borderRadius: widthPixel(4),
    backgroundColor: '#FFFFFF',
    paddingHorizontal: widthPixel(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthText: {
    color: '#444444',
    fontSize: fontPixel(14),
  },
  applyButton: {
    width: widthPixel(96),
    height: heightPixel(43),
    borderRadius: widthPixel(4),
    backgroundColor: '#4A24A8',
    marginLeft: widthPixel(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyButtonText: {
    color: '#FFFFFF',
    fontSize: fontPixel(12),
    fontWeight: '600',
  },
  tabsWrap: {
    marginTop: heightPixel(16),
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    borderBottomWidth: 1,
    borderBottomColor: '#D6D6D6',
  },
  tabButton: {
    flex: 1,
    minHeight: heightPixel(34),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(2),
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabIndicator: {
    position: 'absolute',
    left: 0,
    bottom: -1,
    height: 2,
    backgroundColor: '#000088',
  },
  tabLabel: {
    color: '#1B1B1B',
    fontSize: fontPixel(12),
    textAlign: 'center',
  },
  tabLabelActive: {
    color: '#000088',
    fontWeight: '600',
  },
  summaryCard: {
    // marginTop: heightPixel(10),
    // borderRadius: widthPixel(8),
    backgroundColor: '#DCE9E4',
    paddingHorizontal: widthPixel(34),
    paddingVertical: heightPixel(20),
    flexDirection: 'row',
    alignItems: 'center',
    gap: widthPixel(15),
  },
  summaryIconWrap: {
    width: widthPixel(34),
    height: heightPixel(34),
    borderRadius: widthPixel(17),
    borderWidth: 1,
    borderColor: '#2A2AA6',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E7EDF7',
  },
  summaryTextWrap: {
    marginLeft: widthPixel(10),
  },
  summaryTitle: {
    color: '#444444',
    fontSize: fontPixel(10),
  },
  summaryAmount: {
    color: '#0D0D0D',
    fontSize: fontPixel(24),
    fontWeight: '700',
    marginTop: heightPixel(2),
  },
  animatedContentWrap: {
    flex: 1,
  },
  listContent: {
    // paddingTop: heightPixel(6),
    paddingBottom: heightPixel(16),
  },
  rowSeparator: {
    height: 1,
    backgroundColor: '#DCDCDC',
  },
  emptyStateWrap: {
    paddingVertical: heightPixel(26),
    alignItems: 'center',
  },
  emptyStateText: {
    color: '#6F6F6F',
    fontSize: fontPixel(12),
    fontWeight: '500',
  },
  transactionRow: {
    minHeight: heightPixel(74),
    paddingHorizontal: widthPixel(34),
    paddingVertical: heightPixel(8),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  rowLeft: {
    flex: 1,
  },
  rowTitle: {
    color: '#1F1F1F',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  rowMeta: {
    marginTop: heightPixel(2),
    color: '#666666',
    fontSize: fontPixel(12),
  },
  rowRef: {
    color: '#666666',
    fontSize: fontPixel(12),
    marginTop: heightPixel(2),
  },
  rowRight: {
    alignItems: 'flex-end',
    marginLeft: widthPixel(12),
  },
  rowAmount: {
    color: '#12A246',
    fontSize: fontPixel(20),
    fontWeight: '700',
  },
  rowAmountType: {
    marginTop: heightPixel(2),
    color: '#4F4F4F',
    fontSize: fontPixel(10),
  },
  footer: {
    paddingHorizontal: widthPixel(10),
    paddingTop: heightPixel(8),
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#F0F0F0',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  footerButton: {
    flex: 1,
    height: heightPixel(40),
    borderRadius: widthPixel(4),
    backgroundColor: '#3E2A92',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerButtonGap: {
    marginRight: widthPixel(8),
  },
  footerButtonText: {
    color: '#FFFFFF',
    fontSize: fontPixel(13),
    fontWeight: '700',
  },
  monthPickerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(20),
  },
  monthPickerCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: widthPixel(12),
    paddingHorizontal: widthPixel(14),
    paddingVertical: heightPixel(14),
  },
  monthPickerTitle: {
    color: '#151515',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  monthGrid: {
    marginTop: heightPixel(10),
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: widthPixel(8),
  },
  monthChip: {
    width: '22%',
    height: heightPixel(34),
    borderRadius: widthPixel(6),
    borderWidth: 1,
    borderColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAFAFA',
  },
  monthChipActive: {
    borderColor: '#4A24A8',
    backgroundColor: '#F0EBFF',
  },
  monthChipText: {
    color: '#444444',
    fontSize: fontPixel(11),
    fontWeight: '500',
  },
  monthChipTextActive: {
    color: '#4A24A8',
    fontWeight: '700',
  },
  yearPickerTitle: {
    marginTop: heightPixel(12),
    color: '#4F4F4F',
    fontSize: fontPixel(12),
    fontWeight: '600',
  },
  yearList: {
    paddingTop: heightPixel(8),
    paddingBottom: heightPixel(4),
    columnGap: widthPixel(8),
  },
  yearChip: {
    minWidth: widthPixel(56),
    height: heightPixel(34),
    borderRadius: widthPixel(6),
    borderWidth: 1,
    borderColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAFAFA',
    paddingHorizontal: widthPixel(10),
  },
  yearChipActive: {
    borderColor: '#4A24A8',
    backgroundColor: '#F0EBFF',
  },
  yearChipText: {
    color: '#444444',
    fontSize: fontPixel(11),
    fontWeight: '500',
  },
  yearChipTextActive: {
    color: '#4A24A8',
    fontWeight: '700',
  },
  monthPickerActions: {
    marginTop: heightPixel(14),
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  monthPickerButton: {
    minWidth: widthPixel(84),
    height: heightPixel(36),
    borderRadius: widthPixel(6),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(12),
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: '#CFCFCF',
    backgroundColor: '#FFFFFF',
    marginRight: widthPixel(8),
  },
  cancelButtonText: {
    color: '#555555',
    fontSize: fontPixel(12),
    fontWeight: '600',
  },
  doneButton: {
    backgroundColor: '#4A24A8',
  },
  doneButtonText: {
    color: '#FFFFFF',
    fontSize: fontPixel(12),
    fontWeight: '700',
  },
});
