import { StyleSheet } from 'react-native';
import { fontPixel, heightPixel, widthPixel } from '../../utility/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  header: {
    height: heightPixel(62),
    paddingHorizontal: widthPixel(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconWrap: {
    height: heightPixel(38),
    width: widthPixel(38),
    borderRadius: widthPixel(50),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: fontPixel(20),
    fontWeight: '600',
  },
  contentContainer: {
    paddingHorizontal: widthPixel(12),
    paddingTop: heightPixel(27),
    paddingBottom: heightPixel(18),
  },
  profileCard: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#CFCFCF',
    borderRadius: widthPixel(10),
    paddingHorizontal: widthPixel(20),
    paddingVertical: heightPixel(20),
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: widthPixel(20),
  },
  avatarWrap: {
    width: widthPixel(89),
    height: heightPixel(89),
    borderRadius: widthPixel(50),
    backgroundColor: '#1E1E1E',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  avatarInitials: {
    color: '#FFFFFF',
    fontSize: fontPixel(16),
    fontWeight: '700',
  },
  avatarEditBadge: {
    position: 'absolute',
    right: -5,
    bottom: 0,
    width: widthPixel(26),
    height: heightPixel(26),
    borderRadius: widthPixel(50),
    backgroundColor: '#16A34A',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInfoWrap: {
    marginLeft: widthPixel(12),
    flex: 1,
    rowGap: heightPixel(3),
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoText: {
    marginLeft: widthPixel(7),
    color: '#222222',
    fontSize: fontPixel(12),
    fontWeight: '500',
  },
  infoStrongText: {
    fontWeight: '700',
  },
  cardStack: {
    marginTop: heightPixel(8),
    rowGap: heightPixel(12),
  },
  miniCard: {
    minHeight: heightPixel(40),
    borderWidth: 1,
    borderColor: '#CFCFCF',
    borderRadius: widthPixel(10),
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: widthPixel(16),
    paddingVertical: heightPixel(12),
    gap: widthPixel(6),
  },
  miniCardIconWrap: {
    width: widthPixel(51),
    height: heightPixel(51),
    borderRadius: widthPixel(50),
    backgroundColor: '#E6DBF1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniCardContent: {
    marginLeft: widthPixel(10),
    flex: 1,
  },
  miniCardLabel: {
    color: '#777777',
    fontSize: fontPixel(12),
  },
  miniCardValue: {
    marginTop: heightPixel(2),
    color: '#111111',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  miniCardUberBadge: {
    width: widthPixel(51),
    height: heightPixel(51),
    borderRadius: widthPixel(50),
    backgroundColor: '#E6DBF1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniCardUberText: {
    color: '#4E4E4E',
    fontSize: fontPixel(8),
    fontWeight: '700',
  },
  uberDot: {
    position: 'absolute',
    right: widthPixel(86),
    top: heightPixel(8),
    width: widthPixel(5),
    height: heightPixel(5),
    borderRadius: widthPixel(3),
    backgroundColor: '#E61E24',
  },
  sectionTitle: {
    marginTop: heightPixel(19),
    color: '#1A1A1A',
    fontSize: fontPixel(16),
    fontWeight: '700',
  },
  managerCard: {
    marginTop: heightPixel(6),
    borderWidth: 1,
    borderColor: '#CFCFCF',
    borderRadius: widthPixel(10),
    backgroundColor: 'white',
    paddingHorizontal: widthPixel(18),
    paddingVertical: heightPixel(20),
    rowGap: heightPixel(8),
  },
  managerRow: {
    rowGap: heightPixel(2),
  },
  managerLabel: {
    color: '#777777',
    fontSize: fontPixel(12),
  },
  managerValue: {
    color: '#111111',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  logoutWrap: {
    marginTop: heightPixel(12),
  },
  logoutButton: {
    height: heightPixel(42),
    borderRadius: widthPixel(4),
    backgroundColor: '#352487',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutText: {
    color: '#FFFFFF',
    fontSize: fontPixel(13),
    fontWeight: '700',
  },
});
