import { StyleSheet } from 'react-native';
import { fontPixel, heightPixel, widthPixel } from '../../utility/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  requestScreenContainer: {
    backgroundColor: '#F5F5F5',
  },
  scheduleEditContainer: {
    backgroundColor: '#ECECEC',
  },
  header: {
    height: heightPixel(62),
    paddingHorizontal: widthPixel(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconWrap: {
    height: heightPixel(38),
    width: widthPixel(38),
    borderRadius: widthPixel(50),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: fontPixel(18),
    textAlign: 'center',
  },
  requestHeaderTitle: {
    maxWidth: '72%',
    textAlign: 'center',
    color: '#FFFFFF',
    fontSize: fontPixel(12),
    lineHeight: heightPixel(15),
    fontWeight: '600',
  },
  content: {
    paddingHorizontal: widthPixel(21),
    paddingTop: heightPixel(8),
    paddingBottom: heightPixel(16),
  },
  scheduleEditContent: {
    paddingHorizontal: widthPixel(18),
    paddingTop: heightPixel(10),
    paddingBottom: heightPixel(16),
    flexGrow: 1,
  },
  scheduleSetupCard: {
    borderWidth: 1,
    borderColor: '#CECECE',
    borderRadius: widthPixel(12),
    backgroundColor: '#F7F7F7',
    paddingHorizontal: widthPixel(18),
    paddingVertical: heightPixel(18),
    marginTop: heightPixel(10),
  },
  scheduleSetupTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  workdaySetupLabel: {
    color: '#372A7A',
    fontSize: fontPixel(12),
    fontWeight: '600',
  },
  activeDaysLabel: {
    color: '#372A7A',
    fontSize: fontPixel(12),
    fontWeight: '700',
  },
  scheduleSetupTitle: {
    marginTop: heightPixel(4),
    color: '#101010',
    fontSize: fontPixel(18),
    fontWeight: '700',
  },
  scheduleSetupSubTitle: {
    marginTop: heightPixel(2),
    color: '#7A7A7A',
    fontSize: fontPixel(12),
  },
  shiftHeadingRow: {
    marginTop: heightPixel(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: widthPixel(4),
  },
  shiftHeadingText: {
    color: '#6D6D6D',
    fontSize: fontPixel(12),
    width: '48%',
  },
  shiftRow: {
    marginTop: heightPixel(6),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  shiftSelectorBox: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#D4D4D4',
    borderRadius: widthPixel(8),
    backgroundColor: '#FFFFFF',
    paddingHorizontal: widthPixel(8),
    paddingVertical: heightPixel(6),
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: heightPixel(62),
    gap: widthPixel(6),
  },
  shiftClockWrap: {
    width: widthPixel(36),
    height: heightPixel(36),
    borderRadius: widthPixel(50),
    borderWidth: 1,
    borderColor: '#D8D8D8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: widthPixel(6),
  },
  shiftSmallText: {
    color: '#9A9A9A',
    fontSize: fontPixel(12),
    fontWeight: '500',
  },
  shiftMainText: {
    color: '#2C2C2C',
    fontSize: fontPixel(16),
    fontWeight: '700',
    marginTop: heightPixel(1),
  },
  daysHeadingRow: {
    marginTop: heightPixel(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  daysHeadingText: {
    color: '#94A3B8',
    fontSize: fontPixel(13),
    fontWeight: "700"
  },
  daysTapToEditText: {
    color: '#94A3B8',
    fontSize: fontPixel(12),
    fontWeight: '700',
  },
  daysGridWrap: {
    marginTop: heightPixel(6),
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: heightPixel(8),
  },
  workDayPill: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#D8D8D8',
    borderRadius: widthPixel(18),
    backgroundColor: '#F2F2F2',
    paddingHorizontal: widthPixel(32),
    paddingVertical: heightPixel(5),
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: heightPixel(42),
    gap: widthPixel(6),
  },
  workDayPillActive: {
    backgroundColor: '#332A83',
    borderColor: '#332A83',
  },
  workDayBadge: {
    width: widthPixel(20),
    height: heightPixel(20),
    borderRadius: widthPixel(10),
    // borderWidth: 1,
    // borderColor: '#D4D4D4',
    backgroundColor: '#F5F8FB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: widthPixel(6),
  },
  workDayBadgeActive: {
    backgroundColor: '#4C43A8',
    borderColor: '#4C43A8',
  },
  workDayBadgeText: {
    color: '#8C8C8C',
    fontSize: fontPixel(10),
    fontWeight: '700',
  },
  workDayBadgeTextActive: {
    color: '#FFFFFF',
  },
  workDayLabel: {
    color: '#94A3B8',
    fontSize: fontPixel(14),
    fontWeight: '600',
  },
  workDayLabelActive: {
    color: '#FFFFFF',
  },
  scheduleEditFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: widthPixel(20),
    paddingTop: heightPixel(8),
    backgroundColor: '#ECECEC',
  },
  cancelButton: {
    width: '43%',
    height: heightPixel(50),
    borderWidth: 1,
    borderColor: '#5C5C5C',
    borderRadius: widthPixel(8),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECECEC',
  },
  cancelButtonText: {
    color: '#3F3F3F',
    fontSize: fontPixel(16),
  },
  saveButton: {
    width: '47%',
    height: heightPixel(50),
    borderRadius: widthPixel(8),
    backgroundColor: '#3B2A8F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: fontPixel(16),
  },
  requestContent: {
    paddingHorizontal: widthPixel(16),
    paddingTop: heightPixel(12),
    paddingBottom: heightPixel(16),
    flexGrow: 1,
  },
  requestFieldWrap: {
    marginBottom: heightPixel(12),
  },
  requestFieldLabel: {
    color: '#666666',
    fontSize: fontPixel(14),
    marginBottom: heightPixel(4),
  },
  requiredMark: {
    color: '#D85151',
  },
  requestInputBox: {
    height: heightPixel(43),
    borderWidth: 1,
    borderColor: '#D5D5D5',
    borderRadius: widthPixel(2),
    backgroundColor: '#F5F5F5',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: widthPixel(8),
  },
  requestInputIcon: {
    marginRight: widthPixel(8),
  },
  requestInputValue: {
    color: '#4A4A4A',
    fontSize: fontPixel(16),
  },
  remarksBox: {
    minHeight: heightPixel(102),
    borderWidth: 1,
    borderColor: '#D5D5D5',
    borderRadius: widthPixel(2),
    backgroundColor: '#F5F5F5',
    paddingHorizontal: widthPixel(8),
    paddingVertical: heightPixel(7),
  },
  remarksTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  remarksInput: {
    flex: 1,
    minHeight: heightPixel(118),
    color: '#4A4A4A',
    fontSize: fontPixel(12),
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: widthPixel(6),
  },
  voiceButton: {
    width: widthPixel(28),
    height: heightPixel(28),
    borderWidth: 1,
    borderColor: '#D3D3D3',
    borderRadius: widthPixel(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceButtonRecording: {
    borderColor: '#F2B3B3',
    backgroundColor: '#FFF3F3',
  },
  voiceStatusText: {
    marginTop: heightPixel(6),
    color: '#7C7C7C',
    fontSize: fontPixel(10),
  },
  recordingPreviewRow: {
    marginTop: heightPixel(8),
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: widthPixel(6),
    paddingHorizontal: widthPixel(10),
    paddingVertical: heightPixel(8),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  recordingPreviewPlayWrap: {
    width: widthPixel(24),
    height: heightPixel(24),
    borderRadius: widthPixel(12),
    backgroundColor: '#4B2AAA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordingPreviewTextWrap: {
    marginLeft: widthPixel(8),
    flex: 1,
  },
  recordingPreviewTitle: {
    color: '#666666',
    fontSize: fontPixel(12),
    fontWeight: '600',
  },
  recordingPreviewTime: {
    marginTop: heightPixel(1),
    color: '#666666',
    fontSize: fontPixel(10),
  },
  recordingDeleteButton: {
    width: widthPixel(24),
    height: heightPixel(24),
    borderRadius: widthPixel(12),
    borderWidth: 1,
    borderColor: '#F3CCCC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  remarksCounter: {
    alignSelf: 'flex-end',
    color: '#9A9A9A',
    fontSize: fontPixel(10),
    marginTop: heightPixel(4),
  },
  rosterCard: {
    // borderWidth: 1,
    // borderColor: '#DCDCDC',
    borderRadius: widthPixel(6),
    backgroundColor: '#FFFFFF',
    // paddingHorizontal: widthPixel(10),
    // paddingVertical: heightPixel(10),
  },
  rosterTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: heightPixel(10),
  },
  rosterTitle: {
    color: '#2B0187',
    fontSize: fontPixel(16),
    fontWeight: '700',
  },
  rosterHoursRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#D4D4D4',
    padding: widthPixel(14),
    borderRadius: widthPixel(10)
  },
  rosterLabel: {
    color: '#A0A0A0',
    fontSize: fontPixel(12),
  },
  rosterHoursValue: {
    marginTop: heightPixel(1),
    color: '#101010',
    fontSize: fontPixel(14),
    fontWeight: '700',
  },
  daysWrap: {
    alignItems: 'flex-start',
  },
  dayCircleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: heightPixel(2),
  },
  dayCircle: {
    width: widthPixel(16),
    height: heightPixel(16),
    borderRadius: widthPixel(8),
    backgroundColor: '#F1F1F1',
    borderWidth: 1,
    borderColor: '#DEDEDE',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: widthPixel(3),
  },
  dayText: {
    color: '#666666',
    fontSize: fontPixel(8),
    fontWeight: '600',
  },
  sectionTitle: {
    marginTop: heightPixel(10),
    color: '#1E1E7C',
    fontSize: fontPixel(16),
    fontWeight: '700',
  },
  requestCard: {
    marginTop: heightPixel(8),
    borderWidth: 1,
    borderColor: '#DCDCDC',
    borderRadius: widthPixel(6),
    backgroundColor: '#FFFFFF',
    paddingHorizontal: widthPixel(13),
    paddingVertical: heightPixel(13),
  },
  requestTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  requestDateWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: widthPixel(50),
  },
  requestDateItem: {
    marginRight: widthPixel(12),
  },
  requestDateLabel: {
    color: '#8E8E8E',
    fontSize: fontPixel(14),
  },
  requestDateValue: {
    marginTop: heightPixel(1),
    color: '#2A2A2A',
    fontSize: fontPixel(16),
  },
  statusBadge: {
    minWidth: widthPixel(56),
    height: heightPixel(20),
    borderRadius: widthPixel(10),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPixel(8),
  },
  statusText: {
    fontSize: fontPixel(9),
    fontWeight: '700',
  },
  remarksLabel: {
    marginTop: heightPixel(8),
    color: '#8E8E8E',
    fontSize: fontPixel(14),
  },
  remarksText: {
    marginTop: heightPixel(2),
    color: '#3C3C3C',
    fontSize: fontPixel(16),
  },
  requestDivider: {
    marginTop: heightPixel(8),
    borderTopWidth: 1,
    borderTopColor: '#EEEEEE',
  },
  recordingRow: {
    marginTop: heightPixel(8),
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    padding: widthPixel(13),
    borderColor: "#DDDDDD",
    borderRadius: widthPixel(6)
  },
  playWrap: {
    width: widthPixel(26),
    height: heightPixel(26),
    borderRadius: widthPixel(50),
    backgroundColor: '#4B2AAA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordingTextWrap: {
    marginLeft: widthPixel(6),
  },
  recordingTitle: {
    color: '#666666',
    fontSize: fontPixel(12),
    fontWeight: '600',
  },
  recordingTime: {
    marginTop: heightPixel(1),
    color: '#666666',
    fontSize: fontPixel(10),
  },
  footer: {
    paddingHorizontal: widthPixel(21),
    paddingTop: heightPixel(8),
    backgroundColor: 'white',
  },
  applyButton: {
    height: heightPixel(38),
    borderRadius: widthPixel(4),
    backgroundColor: '#3D2A92',
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyButtonText: {
    color: '#FFFFFF',
    fontSize: fontPixel(12),
    fontWeight: '700',
  },
});
